// <auto-generated />
using System;
using ChatKingsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatKingsApp.MigrationsPostgres
{
    [DbContext(typeof(ChatKingsPostgresDbContext))]
    partial class ChatKingsPostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatKingsApp.Models.Chat", b =>
                {
                    b.Property<int>("chat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("chat_id"));

                    b.Property<int?>("chat_king_user_id")
                        .HasColumnType("integer");

                    b.Property<string>("chat_name")
                        .HasColumnType("text");

                    b.Property<string>("chat_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("created_by_user_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("chat_id");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatLeaderboardSnapshot", b =>
                {
                    b.Property<int>("snapshot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("snapshot_id"));

                    b.Property<int>("chat_id")
                        .HasColumnType("integer");

                    b.Property<int>("points_balance")
                        .HasColumnType("integer");

                    b.Property<int>("rank_position")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("snapshot_date")
                        .HasColumnType("date");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("snapshot_id");

                    b.ToTable("chat_leaderboard_snapshots", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatMember", b =>
                {
                    b.Property<int>("chat_member_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("chat_member_id"));

                    b.Property<int>("chat_id")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_king")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("joined_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("left_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("points_balance")
                        .HasColumnType("integer");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("chat_member_id");

                    b.ToTable("chat_members", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatMessage", b =>
                {
                    b.Property<int>("message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("message_id"));

                    b.Property<int>("chat_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("message_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("message_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("prediction_id")
                        .HasColumnType("integer");

                    b.Property<int>("sender_user_id")
                        .HasColumnType("integer");

                    b.HasKey("message_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatTeam", b =>
                {
                    b.Property<int>("chat_team_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("chat_team_id"));

                    b.Property<DateTime>("added_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("chat_id")
                        .HasColumnType("integer");

                    b.Property<int>("team_id")
                        .HasColumnType("integer");

                    b.HasKey("chat_team_id");

                    b.ToTable("chat_teams", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.FriendRequest", b =>
                {
                    b.Property<int>("request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("request_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("receiver_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("responded_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("sender_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("request_id");

                    b.ToTable("friend_requests", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Friendship", b =>
                {
                    b.Property<int>("friendship_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("friendship_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("user_id_1")
                        .HasColumnType("integer");

                    b.Property<int>("user_id_2")
                        .HasColumnType("integer");

                    b.HasKey("friendship_id");

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Game", b =>
                {
                    b.Property<int>("game_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("game_id"));

                    b.Property<int?>("away_score")
                        .HasColumnType("integer");

                    b.Property<int>("away_team_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("game_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("home_score")
                        .HasColumnType("integer");

                    b.Property<int>("home_team_id")
                        .HasColumnType("integer");

                    b.Property<string>("season")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("venue")
                        .HasColumnType("text");

                    b.HasKey("game_id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.GameTeamStat", b =>
                {
                    b.Property<int>("stat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("stat_id"));

                    b.Property<int?>("assists")
                        .HasColumnType("integer");

                    b.Property<int?>("blocks")
                        .HasColumnType("integer");

                    b.Property<int?>("field_goals_attempted")
                        .HasColumnType("integer");

                    b.Property<int?>("field_goals_made")
                        .HasColumnType("integer");

                    b.Property<int?>("fouls")
                        .HasColumnType("integer");

                    b.Property<int?>("free_throws_attempted")
                        .HasColumnType("integer");

                    b.Property<int?>("free_throws_made")
                        .HasColumnType("integer");

                    b.Property<int>("game_id")
                        .HasColumnType("integer");

                    b.Property<int?>("rebounds")
                        .HasColumnType("integer");

                    b.Property<int?>("steals")
                        .HasColumnType("integer");

                    b.Property<int>("team_id")
                        .HasColumnType("integer");

                    b.Property<int?>("three_pointers_attempted")
                        .HasColumnType("integer");

                    b.Property<int?>("three_pointers_made")
                        .HasColumnType("integer");

                    b.Property<int?>("turnovers")
                        .HasColumnType("integer");

                    b.HasKey("stat_id");

                    b.ToTable("game_team_stats", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.PointsLedger", b =>
                {
                    b.Property<int>("ledger_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ledger_id"));

                    b.Property<int>("change_amount")
                        .HasColumnType("integer");

                    b.Property<string>("change_reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("chat_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("prediction_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.Property<int?>("wager_id")
                        .HasColumnType("integer");

                    b.HasKey("ledger_id");

                    b.ToTable("points_ledger", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Prediction", b =>
                {
                    b.Property<int>("prediction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("prediction_id"));

                    b.Property<int>("chat_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("created_by_user_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("espn_event_id")
                        .HasColumnType("text");

                    b.Property<int>("game_id")
                        .HasColumnType("integer");

                    b.Property<int>("initial_bet_max")
                        .HasColumnType("integer");

                    b.Property<int>("initial_bet_min")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("lock_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("pot_points")
                        .HasColumnType("integer");

                    b.Property<string>("prediction_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("resolved_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("prediction_id");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.PredictionOption", b =>
                {
                    b.Property<int>("option_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("option_id"));

                    b.Property<int>("display_order")
                        .HasColumnType("integer");

                    b.Property<string>("option_label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("prediction_id")
                        .HasColumnType("integer");

                    b.Property<int?>("team_id")
                        .HasColumnType("integer");

                    b.HasKey("option_id");

                    b.HasIndex("prediction_id");

                    b.ToTable("prediction_options", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.PredictionResolution", b =>
                {
                    b.Property<int>("resolution_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("resolution_id"));

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<int>("prediction_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("resolved_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("resolved_by_user_id")
                        .HasColumnType("integer");

                    b.Property<int>("winning_option_id")
                        .HasColumnType("integer");

                    b.HasKey("resolution_id");

                    b.ToTable("prediction_resolutions", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.StrikeEvent", b =>
                {
                    b.Property<int>("strike_event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("strike_event_id"));

                    b.Property<int>("chat_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("strike_value")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("strike_event_id");

                    b.ToTable("strike_events", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Team", b =>
                {
                    b.Property<int>("team_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("team_id"));

                    b.Property<string>("conference")
                        .HasColumnType("text");

                    b.Property<string>("division")
                        .HasColumnType("text");

                    b.Property<string>("league")
                        .HasColumnType("text");

                    b.Property<string>("team_abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("team_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("team_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<string>("add_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("lifetime_points")
                        .HasColumnType("integer");

                    b.Property<string>("password_hash")
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .HasColumnType("text");

                    b.Property<string>("profile_image_url")
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Wager", b =>
                {
                    b.Property<int>("wager_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("wager_id"));

                    b.Property<int>("chat_id")
                        .HasColumnType("integer");

                    b.Property<int>("option_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("placed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("points_wagered")
                        .HasColumnType("integer");

                    b.Property<int>("prediction_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("resolved_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("result_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("wager_id");

                    b.HasIndex("option_id");

                    b.HasIndex("prediction_id");

                    b.ToTable("wagers", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.PredictionOption", b =>
                {
                    b.HasOne("ChatKingsApp.Models.Prediction", null)
                        .WithMany("Options")
                        .HasForeignKey("prediction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatKingsApp.Models.Wager", b =>
                {
                    b.HasOne("ChatKingsApp.Models.PredictionOption", "PredictionOption")
                        .WithMany("Wagers")
                        .HasForeignKey("option_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatKingsApp.Models.Prediction", "Prediction")
                        .WithMany("Wagers")
                        .HasForeignKey("prediction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prediction");

                    b.Navigation("PredictionOption");
                });

            modelBuilder.Entity("ChatKingsApp.Models.Prediction", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Wagers");
                });

            modelBuilder.Entity("ChatKingsApp.Models.PredictionOption", b =>
                {
                    b.Navigation("Wagers");
                });
#pragma warning restore 612, 618
        }
    }
}
