// <auto-generated />
using System;
using ChatKingsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatKingsApp.Migrations
{
    [DbContext(typeof(ChatKingsDbContext))]
    [Migration("20260318023104_Initial1")]
    partial class Initial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ChatKingsApp.Models.Bet", b =>
                {
                    b.Property<int>("bet_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bet_category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("chat_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("placed_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("points_wagered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("prediction_details_json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("resolved_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("bet_id");

                    b.ToTable("BETS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.BetHistory", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("bet_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("chat_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("points_change")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("recorded_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("history_id");

                    b.ToTable("BET_HISTORY", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Chat", b =>
                {
                    b.Property<int>("chat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("admin_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("bet_permission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("chat_name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("chat_id");

                    b.ToTable("CHATS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatMember", b =>
                {
                    b.Property<int>("member_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("chat_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("joined_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("left_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("member_id");

                    b.ToTable("CHAT_MEMBERS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatTeam", b =>
                {
                    b.Property<int>("chat_team_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("added_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("chat_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("team_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("chat_team_id");

                    b.ToTable("CHAT_TEAMS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.DailyStrike", b =>
                {
                    b.Property<int>("strike_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("chat_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("strike_count")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("strike_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("strike_id");

                    b.ToTable("DAILY_STRIKES", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.FriendRequest", b =>
                {
                    b.Property<int>("request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("receiver_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("responded_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("sender_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("request_id");

                    b.ToTable("FRIEND_REQUESTS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Friendship", b =>
                {
                    b.Property<int>("friendship_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("user_id_2")
                        .HasColumnType("INTEGER");

                    b.HasKey("friendship_id");

                    b.ToTable("FRIENDSHIPS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Game", b =>
                {
                    b.Property<int>("game_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("away_score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("away_team_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("game_datetime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("home_score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("home_team_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("venue")
                        .HasColumnType("TEXT");

                    b.HasKey("game_id");

                    b.ToTable("GAMES", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.GameStat", b =>
                {
                    b.Property<int>("stat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("other_stats_json")
                        .HasColumnType("TEXT");

                    b.Property<int?>("passing_yards")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("rushing_yards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("team_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("time_of_possession_seconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("total_yards")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("turnovers")
                        .HasColumnType("INTEGER");

                    b.HasKey("stat_id");

                    b.ToTable("GAME_STATS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Message", b =>
                {
                    b.Property<int>("message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("chat_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("message_text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("message_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("related_bet_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("sent_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("message_id");

                    b.ToTable("MESSAGES", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Team", b =>
                {
                    b.Property<int>("team_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("conference")
                        .HasColumnType("TEXT");

                    b.Property<string>("league")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("logo_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("team_abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("team_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("team_id");

                    b.ToTable("TEAMS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("add_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("all_time_points")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("phone_number")
                        .HasColumnType("TEXT");

                    b.Property<string>("profile_image_url")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("user_id");

                    b.ToTable("USERS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
