// <auto-generated />
using System;
using ChatKingsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatKingsApp.Migrations
{
    [DbContext(typeof(ChatKingsDbContext))]
    partial class ChatKingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ChatKingsApp.Models.BotHistory", b =>
                {
                    b.Property<int>("BotHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTurnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BotHistoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("GameTurnId");

                    b.HasIndex("UserId");

                    b.ToTable("BOT_HISTORY", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatTeam", b =>
                {
                    b.Property<int>("ChatThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatThreadId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("CHAT_TEAMS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatThread", b =>
                {
                    b.Property<int>("ChatThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatThreadId");

                    b.HasIndex("GameId");

                    b.ToTable("CHAT_THREADS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Friendship", b =>
                {
                    b.Property<int>("RequestorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddresseeUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequestorUserId", "AddresseeUserId");

                    b.HasIndex("AddresseeUserId");

                    b.ToTable("FRIENDSHIPS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HostUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.HasIndex("HostUserId");

                    b.ToTable("GAMES", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.GameStat", b =>
                {
                    b.Property<int>("GameStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameStatId");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.ToTable("GAME_STATS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.GameTurn", b =>
                {
                    b.Property<int>("GameTurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActingUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameTurnId");

                    b.HasIndex("ActingUserId");

                    b.HasIndex("GameId");

                    b.ToTable("TURNS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatThreadId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("MESSAGES", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.OpenGame", b =>
                {
                    b.Property<int>("OpenGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HostUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OpenGameId");

                    b.HasIndex("GameId");

                    b.HasIndex("HostUserId");

                    b.ToTable("OPEN", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.PublicProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AboutMe")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("PUBLIC_PROFILES", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId");

                    b.HasIndex("GameId");

                    b.ToTable("TEAMS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthProviderUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("ChatKingsApp.Models.BotHistory", b =>
                {
                    b.HasOne("ChatKingsApp.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatKingsApp.Models.GameTurn", "GameTurn")
                        .WithMany()
                        .HasForeignKey("GameTurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatKingsApp.Models.User", "User")
                        .WithMany("BotHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameTurn");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatTeam", b =>
                {
                    b.HasOne("ChatKingsApp.Models.ChatThread", "ChatThread")
                        .WithMany("ChatTeams")
                        .HasForeignKey("ChatThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatKingsApp.Models.Team", "Team")
                        .WithMany("ChatTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatThread");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatThread", b =>
                {
                    b.HasOne("ChatKingsApp.Models.Game", "Game")
                        .WithMany("ChatThreads")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChatKingsApp.Models.Friendship", b =>
                {
                    b.HasOne("ChatKingsApp.Models.User", "AddresseeUser")
                        .WithMany("FriendshipsReceived")
                        .HasForeignKey("AddresseeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatKingsApp.Models.User", "RequestorUser")
                        .WithMany("FriendshipsRequested")
                        .HasForeignKey("RequestorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddresseeUser");

                    b.Navigation("RequestorUser");
                });

            modelBuilder.Entity("ChatKingsApp.Models.Game", b =>
                {
                    b.HasOne("ChatKingsApp.Models.User", "HostUser")
                        .WithMany("GamesHosted")
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("ChatKingsApp.Models.GameStat", b =>
                {
                    b.HasOne("ChatKingsApp.Models.Game", "Game")
                        .WithMany("GameStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatKingsApp.Models.Team", "Team")
                        .WithMany("GameStats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ChatKingsApp.Models.GameTurn", b =>
                {
                    b.HasOne("ChatKingsApp.Models.User", "ActingUser")
                        .WithMany("GameTurns")
                        .HasForeignKey("ActingUserId");

                    b.HasOne("ChatKingsApp.Models.Game", "Game")
                        .WithMany("Turns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActingUser");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChatKingsApp.Models.Message", b =>
                {
                    b.HasOne("ChatKingsApp.Models.ChatThread", "ChatThread")
                        .WithMany("Messages")
                        .HasForeignKey("ChatThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatKingsApp.Models.User", "SenderUser")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatThread");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("ChatKingsApp.Models.OpenGame", b =>
                {
                    b.HasOne("ChatKingsApp.Models.Game", "Game")
                        .WithMany("OpenGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatKingsApp.Models.User", "HostUser")
                        .WithMany()
                        .HasForeignKey("HostUserId");

                    b.Navigation("Game");

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("ChatKingsApp.Models.PublicProfile", b =>
                {
                    b.HasOne("ChatKingsApp.Models.User", "User")
                        .WithOne("PublicProfile")
                        .HasForeignKey("ChatKingsApp.Models.PublicProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatKingsApp.Models.Team", b =>
                {
                    b.HasOne("ChatKingsApp.Models.Game", "Game")
                        .WithMany("Teams")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChatKingsApp.Models.ChatThread", b =>
                {
                    b.Navigation("ChatTeams");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ChatKingsApp.Models.Game", b =>
                {
                    b.Navigation("ChatThreads");

                    b.Navigation("GameStats");

                    b.Navigation("OpenGames");

                    b.Navigation("Teams");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("ChatKingsApp.Models.Team", b =>
                {
                    b.Navigation("ChatTeams");

                    b.Navigation("GameStats");
                });

            modelBuilder.Entity("ChatKingsApp.Models.User", b =>
                {
                    b.Navigation("BotHistories");

                    b.Navigation("FriendshipsReceived");

                    b.Navigation("FriendshipsRequested");

                    b.Navigation("GameTurns");

                    b.Navigation("GamesHosted");

                    b.Navigation("MessagesSent");

                    b.Navigation("PublicProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
